steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/lunch-bot', '.']

  # Push the Docker image to the Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/lunch-bot']

  # Deploy to Google Cloud Run in europe-west1 region
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'lunch-bot-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/lunch-bot'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
